### ISSUE TITLE
Shows a message about an update on latest version

### ISSUE THREAD

**Issue by GrafKiedyOdcinek** [Unofficial-Filman-Client/unofficial-filman-client#23]
I installed 1.2.2 from this github page, but when I open the app it says that I have 1.2.1 and when I update it still shows the same message.

**Comment by majusss** [comment]
i reproduced ur issue, idk how it happend but i will try rerun github workflow

**Comment by majusss** [comment]
Fixed in #25. You can check and close this issue

**Comment by GrafKiedyOdcinek** [comment]
I still experience the same issue, but now it says that I should update to 1.2.3 and when I do it installs 1.2.2. I downloaded the apk from GitHub.

**Comment by majusss** [comment]
Thats so weird

**Comment by majusss** [comment]
Fixed in 1.3.0.
